import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
  name: "MiniSuperApp",
  projects: [
    "Projects/App",
    "Projects/Feature/Splash/Sample",
    "Projects/Feature/LoggedOut/Sample"
  ],
  generationOptions: .options(
    enableAutomaticXcodeSchemes: true,
    autogeneratedWorkspaceSchemes: .enabled(codeCoverageMode: .relevant)
  )
)
