import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
  name: "MiniSuperApp",
  projects: [
    "Projects/App"
  ],
  generationOptions: .options(
    enableAutomaticXcodeSchemes: false,
    autogeneratedWorkspaceSchemes: .enabled(
      codeCoverageMode: .relevant,
      testingOptions: []
    )
  )
)
