///
/// @Generated by Mockolo
///

import AppTestSupport
import Foundation
@testable import MiniSuperApp
import RIBs
import RxRelay
import RxSwift
import SplashInterface
import UIKit

// MARK: - RootInteractableMock

final class RootInteractableMock: RootInteractable {
  init() {}
  init(
    router: RootRouting? = nil,
    listener: RootListener? = nil,
    isActive: Bool = false,
    isActiveStream: Observable<Bool> = PublishSubject<Bool>()
  ) {
    self.router = router
    self.listener = listener
    self.isActive = isActive
    self.isActiveStream = isActiveStream
  }

  public private(set) var initializationCompleteCallCount = 0

  private(set) var routerSetCallCount = 0
  var router: RootRouting? { didSet { self.routerSetCallCount += 1 } }

  private(set) var listenerSetCallCount = 0
  var listener: RootListener? { didSet { self.listenerSetCallCount += 1 } }
  public var initializationCompleteHandler: (() -> ())?
  public func initializationComplete() {
    self.initializationCompleteCallCount += 1
    if let initializationCompleteHandler = initializationCompleteHandler {
      initializationCompleteHandler()
    }
  }

  public private(set) var isActiveSetCallCount = 0
  public var isActive: Bool = false { didSet { self.isActiveSetCallCount += 1 } }
  private var isActiveStreamSubjectKind = 0
  public private(set) var isActiveStreamSubjectSetCallCount = 0
  public var isActiveStreamSubject = PublishSubject<Bool>() { didSet { isActiveStreamSubjectSetCallCount += 1 } }
  public var isActiveStreamReplaySubject = ReplaySubject<Bool>
    .create(bufferSize: 1) { didSet { self.isActiveStreamSubjectSetCallCount += 1 } }
  public var isActiveStreamBehaviorSubject: BehaviorSubject<Bool>! {
    didSet { self.isActiveStreamSubjectSetCallCount += 1 }
  }

  public var _isActiveStream: Observable<Bool>! { didSet { self.isActiveStreamSubjectSetCallCount += 1 } }
  public var isActiveStream: Observable<Bool> {
    get {
      if self.isActiveStreamSubjectKind == 0 {
        return self.isActiveStreamSubject
      } else if self.isActiveStreamSubjectKind == 1 {
        return self.isActiveStreamBehaviorSubject
      } else if self.isActiveStreamSubjectKind == 2 {
        return self.isActiveStreamReplaySubject
      } else {
        return self._isActiveStream
      }
    }
    set {
      if let val = newValue as? PublishSubject<Bool> {
        self.isActiveStreamSubject = val
        self.isActiveStreamSubjectKind = 0
      } else if let val = newValue as? BehaviorSubject<Bool> {
        self.isActiveStreamBehaviorSubject = val
        self.isActiveStreamSubjectKind = 1
      } else if let val = newValue as? ReplaySubject<Bool> {
        self.isActiveStreamReplaySubject = val
        self.isActiveStreamSubjectKind = 2
      } else {
        self._isActiveStream = newValue
        self.isActiveStreamSubjectKind = 3
      }
    }
  }

  public private(set) var activateCallCount = 0
  public var activateHandler: (() -> Void)?
  public func activate() {
    self.activateCallCount += 1
    if let activateHandler = activateHandler {
      activateHandler()
    }
  }

  public private(set) var deactivateCallCount = 0
  public var deactivateHandler: (() -> Void)?
  public func deactivate() {
    self.deactivateCallCount += 1
    if let deactivateHandler = deactivateHandler {
      deactivateHandler()
    }
  }
}

// MARK: - RootRoutingMock

final class RootRoutingMock: RootRouting {
  init() {}
  init(
    lifecycle: Observable<RouterLifecycle> = PublishSubject<RouterLifecycle>(),
    viewControllable: ViewControllable = ViewControllableMock(),
    interactable: Interactable = InteractableMock(),
    children: [Routing] = [Routing]()
  ) {
    self.lifecycle = lifecycle
    self.viewControllable = viewControllable
    self.interactable = interactable
    self.children = children
  }

  private(set) var attachSplashRIBCallCount = 0
  var attachSplashRIBHandler: (() -> ())?
  func attachSplashRIB() {
    self.attachSplashRIBCallCount += 1
    if let attachSplashRIBHandler = attachSplashRIBHandler {
      attachSplashRIBHandler()
    }
  }

  private(set) var detachSplashRIBCallCount = 0
  var detachSplashRIBHandler: (() -> ())?
  func detachSplashRIB() {
    self.detachSplashRIBCallCount += 1
    if let detachSplashRIBHandler = detachSplashRIBHandler {
      detachSplashRIBHandler()
    }
  }

  private var lifecycleSubjectKind = 0
  public private(set) var lifecycleSubjectSetCallCount = 0
  public var lifecycleSubject = PublishSubject<RouterLifecycle>() { didSet { lifecycleSubjectSetCallCount += 1 } }
  public var lifecycleReplaySubject = ReplaySubject<RouterLifecycle>
    .create(bufferSize: 1) { didSet { self.lifecycleSubjectSetCallCount += 1 } }
  public var lifecycleBehaviorSubject: BehaviorSubject<RouterLifecycle>! {
    didSet { self.lifecycleSubjectSetCallCount += 1 }
  }

  public var _lifecycle: Observable<RouterLifecycle>! { didSet { self.lifecycleSubjectSetCallCount += 1 } }
  public var lifecycle: Observable<RouterLifecycle> {
    get {
      if self.lifecycleSubjectKind == 0 {
        return self.lifecycleSubject
      } else if self.lifecycleSubjectKind == 1 {
        return self.lifecycleBehaviorSubject
      } else if self.lifecycleSubjectKind == 2 {
        return self.lifecycleReplaySubject
      } else {
        return self._lifecycle
      }
    }
    set {
      if let val = newValue as? PublishSubject<RouterLifecycle> {
        self.lifecycleSubject = val
        self.lifecycleSubjectKind = 0
      } else if let val = newValue as? BehaviorSubject<RouterLifecycle> {
        self.lifecycleBehaviorSubject = val
        self.lifecycleSubjectKind = 1
      } else if let val = newValue as? ReplaySubject<RouterLifecycle> {
        self.lifecycleReplaySubject = val
        self.lifecycleSubjectKind = 2
      } else {
        self._lifecycle = newValue
        self.lifecycleSubjectKind = 3
      }
    }
  }

  public private(set) var viewControllableSetCallCount = 0
  public var viewControllable: ViewControllable = ViewControllableMock() {
    didSet { self.viewControllableSetCallCount += 1 }
  }

  public private(set) var interactableSetCallCount = 0
  public var interactable: Interactable = InteractableMock() { didSet { self.interactableSetCallCount += 1 } }
  public private(set) var childrenSetCallCount = 0
  public var children: [Routing] = .init() { didSet { self.childrenSetCallCount += 1 } }
  public private(set) var loadCallCount = 0
  public var loadHandler: (() -> Void)?
  public func load() {
    self.loadCallCount += 1
    if let loadHandler = loadHandler {
      loadHandler()
    }
  }

  public private(set) var attachChildCallCount = 0
  public var attachChildHandler: ((Routing) -> Void)?
  public func attachChild(_ child: Routing) {
    self.attachChildCallCount += 1
    if let attachChildHandler = attachChildHandler {
      attachChildHandler(child)
    }
  }

  public private(set) var detachChildCallCount = 0
  public var detachChildHandler: ((Routing) -> Void)?
  public func detachChild(_ child: Routing) {
    self.detachChildCallCount += 1
    if let detachChildHandler = detachChildHandler {
      detachChildHandler(child)
    }
  }
}

// MARK: - RootPresentableMock

final class RootPresentableMock: RootPresentable {
  init() {}
  init(listener: RootPresentableListener? = nil) {
    self.listener = listener
  }

  private(set) var listenerSetCallCount = 0
  var listener: RootPresentableListener? { didSet { self.listenerSetCallCount += 1 } }
}

// MARK: - RootViewControllableMock

final class RootViewControllableMock: RootViewControllable {
  init() {}
  init(uiviewController: UIViewController = UIViewController()) {
    self.uiviewController = uiviewController
  }

  private(set) var presentCallCount = 0
  var presentHandler: ((ViewControllable, Bool) -> ())?
  func present(_ viewControllable: ViewControllable, animated: Bool) {
    self.presentCallCount += 1
    if let presentHandler = presentHandler {
      presentHandler(viewControllable, animated)
    }
  }

  private(set) var dismissCallCount = 0
  var dismissHandler: ((ViewControllable, Bool) -> ())?
  func dismiss(_ viewController: ViewControllable, animated: Bool) {
    self.dismissCallCount += 1
    if let dismissHandler = dismissHandler {
      dismissHandler(viewController, animated)
    }
  }

  public private(set) var uiviewControllerSetCallCount = 0
  public var uiviewController: UIViewController = .init() { didSet { self.uiviewControllerSetCallCount += 1 } }
}
