//
// @Generated by Mockolo
//

import AppTestSupport
import Foundation
import NetworkInterface
import RIBs
import RxRelay
import RxSwift
import SplashInterface
@testable import Splash

// MARK: - SplashListenerMock

public final class SplashListenerMock: SplashListener {
  public init() {}

  public private(set) var initializationCompleteCallCount = 0
  public var initializationCompleteHandler: (() -> ())?
  public func initializationComplete() {
    initializationCompleteCallCount += 1
    if let initializationCompleteHandler {
      initializationCompleteHandler()
    }
  }
}

// MARK: - BootstrapRepositoryMock

final class BootstrapRepositoryMock: BootstrapRepository {
  init() {}

  private(set) var requestBootstrappingCallCount = 0
  var requestBootstrappingHandler: (() -> (Single<Void>))?
  func requestBootstrapping() -> Single<Void> {
    requestBootstrappingCallCount += 1
    if let requestBootstrappingHandler {
      return requestBootstrappingHandler()
    }
    fatalError("requestBootstrappingHandler returns can't have a default value thus its handler must be set")
  }
}

// MARK: - SplashPresentableMock

final class SplashPresentableMock: SplashPresentable {
  init() {}
  init(listener: SplashPresentableListener? = nil) {
    self.listener = listener
  }

  private(set) var listenerSetCallCount = 0
  var listener: SplashPresentableListener? { didSet { listenerSetCallCount += 1 } }

  private(set) var displaySplashCallCount = 0
  var displaySplashHandler: ((SplashModels.Splash.ViewModel) -> ())?
  func displaySplash(viewModel: SplashModels.Splash.ViewModel) {
    displaySplashCallCount += 1
    if let displaySplashHandler {
      displaySplashHandler(viewModel)
    }
  }

  private(set) var displayBootstrapCallCount = 0
  var displayBootstrapHandler: ((SplashModels.Bootstrap.ViewModel) -> ())?
  func displayBootstrap(viewModel: SplashModels.Bootstrap.ViewModel) {
    displayBootstrapCallCount += 1
    if let displayBootstrapHandler {
      displayBootstrapHandler(viewModel)
    }
  }
}

// MARK: - SplashRoutingMock

public final class SplashRoutingMock: SplashRouting {
  public init() {}
  public init(
    lifecycle: Observable<RouterLifecycle> = PublishSubject<RouterLifecycle>(),
    viewControllable: ViewControllable = ViewControllableMock(),
    interactable: Interactable = InteractableMock(),
    children: [Routing] = [Routing]()
  ) {
    self.lifecycle = lifecycle
    self.viewControllable = viewControllable
    self.interactable = interactable
    self.children = children
  }

  private var lifecycleSubjectKind = 0
  public private(set) var lifecycleSubjectSetCallCount = 0
  public var lifecycleSubject = PublishSubject<RouterLifecycle>() { didSet { lifecycleSubjectSetCallCount += 1 } }
  public var lifecycleReplaySubject = ReplaySubject<RouterLifecycle>
    .create(bufferSize: 1) { didSet { lifecycleSubjectSetCallCount += 1 } }
  public var lifecycleBehaviorSubject: BehaviorSubject<RouterLifecycle>! {
    didSet { lifecycleSubjectSetCallCount += 1 }
  }

  public var _lifecycle: Observable<RouterLifecycle>! { didSet { lifecycleSubjectSetCallCount += 1 } }
  public var lifecycle: Observable<RouterLifecycle> {
    get {
      if lifecycleSubjectKind == 0 {
        return lifecycleSubject
      } else if lifecycleSubjectKind == 1 {
        return lifecycleBehaviorSubject
      } else if lifecycleSubjectKind == 2 {
        return lifecycleReplaySubject
      } else {
        return _lifecycle
      }
    }
    set {
      if let val = newValue as? PublishSubject<RouterLifecycle> {
        lifecycleSubject = val
        lifecycleSubjectKind = 0
      } else if let val = newValue as? BehaviorSubject<RouterLifecycle> {
        lifecycleBehaviorSubject = val
        lifecycleSubjectKind = 1
      } else if let val = newValue as? ReplaySubject<RouterLifecycle> {
        lifecycleReplaySubject = val
        lifecycleSubjectKind = 2
      } else {
        _lifecycle = newValue
        lifecycleSubjectKind = 3
      }
    }
  }

  public private(set) var viewControllableSetCallCount = 0
  public var viewControllable: ViewControllable = ViewControllableMock() {
    didSet { viewControllableSetCallCount += 1 }
  }

  public private(set) var interactableSetCallCount = 0
  public var interactable: Interactable = InteractableMock() { didSet { interactableSetCallCount += 1 } }
  public private(set) var childrenSetCallCount = 0
  public var children: [Routing] = .init() { didSet { childrenSetCallCount += 1 } }
  public private(set) var loadCallCount = 0
  public var loadHandler: (() -> Void)?
  public func load() {
    loadCallCount += 1
    if let loadHandler {
      loadHandler()
    }
  }

  public private(set) var attachChildCallCount = 0
  public var attachChildHandler: ((Routing) -> Void)?
  public func attachChild(_ child: Routing) {
    attachChildCallCount += 1
    if let attachChildHandler {
      attachChildHandler(child)
    }
  }

  public private(set) var detachChildCallCount = 0
  public var detachChildHandler: ((Routing) -> Void)?
  public func detachChild(_ child: Routing) {
    detachChildCallCount += 1
    if let detachChildHandler {
      detachChildHandler(child)
    }
  }
}

// MARK: - SplashBuildableMock

public final class SplashBuildableMock: SplashBuildable {
  public init() {}

  public private(set) var buildCallCount = 0
  public var buildHandler: ((SplashBuildDependency) -> (SplashRouting))?
  public func build(with dynamicBuildDependency: SplashBuildDependency) -> SplashRouting {
    buildCallCount += 1
    if let buildHandler {
      return buildHandler(dynamicBuildDependency)
    }
    return SplashRoutingMock()
  }
}
