//
// @Generated by Mockolo
//

import BootstrapDomain
import Foundation
import RxSwift

public final class BootstrapRepositoryMock: BootstrapRepository {
  public init() {}

  public private(set) var requestBootstrappingCallCount = 0
  public var requestBootstrappingHandler: (() -> (Single<BootstrapModel>))?
  public func requestBootstrapping() -> Single<BootstrapModel> {
    requestBootstrappingCallCount += 1
    if let requestBootstrappingHandler {
      return requestBootstrappingHandler()
    }
    fatalError("requestBootstrappingHandler returns can't have a default value thus its handler must be set")
  }
}
